#pragma once

	// 21 이상부터 시작해야 한다!!!
enum class PACKET_ID : short
{
	INTERNAL_BEGIN = 101,

	INTERNAL_CLOSE = 107,

	INTERNAL_END = 150,

	
	DEV_ECHO = 181,


	LOGIN_REQUEST = 201,
	LOGIN_RESPONSE = 202,

	ROOM_ENTER_REQUEST = 206,
	ROOM_ENTER_RESPONSE = 207,

	ROOM_LEAVE_REQUEST = 216,
	ROOM_LEAVE_RESPONSE = 217,

	ROOM_CHAT_REQUEST = 221,
	ROOM_CHAT_RESPONSE = 222,
	ROOM_CHAT_NOTIFY = 223,
};

